### ISSUE TITLE
Add the possibility to add a custom label to ALL metrics generated

### ISSUE THREAD

**Issue by giorgiodig** [vitalics/playwright-prometheus-remote-write-reporter#11] opened 2024-08-12 09:26 UTC
We are running playwright tests for multiple environments (dev, stage, prod), and it would be very nice to add a custom label support in playwright.config.js,  for ALL metrics generated by playwright, so we can differentiate between environments when building dashboards, alerts, etc.

Right now we are doing a non-ideal thing of creating different prefixes based on the environment, but it is not ideal for us as it:
- generates duplicated metrics
- makes dashboarding harder, as we can't filter by label name, but we have to hardcode metrics name (and prefixes)

Thanks!

**Comment by xTrekStorex** [comment] 2024-08-12 10:38
see #9  & #10

**Comment by vitalics** [comment] 2024-08-13 06:59
close as duplicate of #9

**Closed by vitalics** 2024-08-13 06:59 UTC
Labels: duplicate, enhancement, good first issue, release:0.1
